# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/data2/ue/ue_5_3_2/UnrealEngine
GAMEPROJECTFILE =/home/knight/git/ue/BarriersOvercomer/BarriersOvercomer.uproject

TARGETS = \
	BarriersOvercomer-Linux-Debug  \
	BarriersOvercomer-Linux-DebugGame  \
	BarriersOvercomer-Linux-Test  \
	BarriersOvercomer-Linux-Shipping  \
	BarriersOvercomer \
	BarriersOvercomerEditor-Linux-Debug  \
	BarriersOvercomerEditor-Linux-DebugGame  \
	BarriersOvercomerEditor-Linux-Test  \
	BarriersOvercomerEditor-Linux-Shipping  \
	BarriersOvercomerEditor \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BarriersOvercomerEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BarriersOvercomerEditor-Linux-Debug


BarriersOvercomer-Linux-Debug:
	 $(PROJECTBUILD) BarriersOvercomer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomer-Linux-DebugGame:
	 $(PROJECTBUILD) BarriersOvercomer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomer-Linux-Test:
	 $(PROJECTBUILD) BarriersOvercomer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomer-Linux-Shipping:
	 $(PROJECTBUILD) BarriersOvercomer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomer:
	 $(PROJECTBUILD) BarriersOvercomer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomerEditor-Linux-Debug:
	 $(PROJECTBUILD) BarriersOvercomerEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomerEditor-Linux-DebugGame:
	 $(PROJECTBUILD) BarriersOvercomerEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomerEditor-Linux-Test:
	 $(PROJECTBUILD) BarriersOvercomerEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomerEditor-Linux-Shipping:
	 $(PROJECTBUILD) BarriersOvercomerEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BarriersOvercomerEditor:
	 $(PROJECTBUILD) BarriersOvercomerEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
